### ISSUE TITLE
error: failed to run custom build command for `gdk-pixbuf v0.8.0`

### ISSUE THREAD

**Issue by pepijndevos** [bodil/vgtk#65]
I'm going completely nuts over this one. How to reproduce:

```
cargo generate --git https://github.com/bodil/cargo-template-vgtk
cd somewhere
# optionally update to vgtk to 0.3
cargo build
```

```
error: failed to run custom build command for `gdk-pixbuf v0.9.0`

Caused by:
  process didn't exit successfully: `/home/pepijn/code/asic/tester/target/debug/build/gdk-pixbuf-6ab202b0be096025/build-script-build` (exit code: 101)
  --- stderr
  thread 'main' panicked at 'Doc comments cannot be written everywhere', /home/pepijn/.cargo/registry/src/github.com-1ecc6299db9ec823/rustdoc-stripper-0.1.16/src/strip.rs:670:38
  stack backtrace:
     0: std::panicking::begin_panic
               at /home/pepijn/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:505
     1: stripper_lib::strip::strip_comments
               at /home/pepijn/.cargo/registry/src/github.com-1ecc6299db9ec823/rustdoc-stripper-0.1.16/src/strip.rs:670
     2: lgpl_docs::purge::{{closure}}
               at /home/pepijn/.cargo/registry/src/github.com-1ecc6299db9ec823/gtk-rs-lgpl-docs-0.1.18/src/lib.rs:91
     3: stripper_lib::utils::check_path_type
               at /home/pepijn/.cargo/registry/src/github.com-1ecc6299db9ec823/rustdoc-stripper-0.1.16/src/utils.rs:95
     4: stripper_lib::utils::do_loop_over_files
               at /home/pepijn/.cargo/registry/src/github.com-1ecc6299db9ec823/rustdoc-stripper-0.1.16/src/utils.rs:52
     5: stripper_lib::utils::loop_over_files
               at /home/pepijn/.cargo/registry/src/github.com-1ecc6299db9ec823/rustdoc-stripper-0.1.16/src/utils.rs:31
     6: lgpl_docs::purge
               at /home/pepijn/.cargo/registry/src/github.com-1ecc6299db9ec823/gtk-rs-lgpl-docs-0.1.18/src/lib.rs:91
     7: build_script_build::manage_docs
               at ./build.rs:13
     8: build_script_build::main
               at ./build.rs:2
     9: core::ops::function::FnOnce::call_once
               at /home/pepijn/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:227
```
I'd just report a bug with gdk-pixbuf, but if I *only* add `gdk-pixbuf = "0.8.0"` to my `Cargo.toml` it works fine.
I did have this working a couple of days ago, so I have absolutely no clue what is going on.
I updated to `vgtk = "0.3.0"` which in some weird order of operations made it work earlier today, but can't reproduce.

The bug seems to be related to some weird documentation generation thing deep in the bowels of gtk. I'd be more than happy to just not have it do any documentation stuff...

**Comment by pepijndevos** [comment]
Patching vgtk as follows removes the documentation stuff. No idea what the implications of that are, but fixes my immediate problem.

```
[dependencies.gtk]
version = "0.9.0"
features = ["v3_20"]
```

**Comment by pepijndevos** [comment]
Seems there is a PR already that allows disabling this feature #61
